### ISSUE TITLE
Add --tags

### ISSUE THREAD

**Issue by Cryptjar** [m-ou-se/rust-git-version#2]
I would recommend adding the `--tags` option to the `git` call. According to `git help describe`, the `--tags` option takes also lightweight tags into account, which are those without a tag message.

This change might be essentially interesting for people like me, who just start trying the crate for the first time and simply add a (non-annotated) git tag for testing and wonder why it gets ignored.

**Comment by m-ou-se** [comment]
I don't think `--tags` should be included by default.

The man-page of `git-tag` mentions:

> Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels. For this reason, some git commands for naming objects (like git describe) will ignore lightweight tags by default.

Since lightweight tags are only meant to be used locally, they shouldn't be included in the version by default.

**Comment by Cryptjar** [comment]
Well, that is a fair point.
So I will remove that, that at least proper error handling gets included.
Actually, I began to add a more configurable way which would allow, those interested in `--tags`, to configure it independently of the default setting.
