### ISSUE TITLE
Semver and branch name support

### ISSUE THREAD

**Issue by andreasWallnerIFX** [m-ou-se/rust-git-version#25]
I'd like to use git-version to generate version identifiers for e.g. CI builds (as they are downloaded and used by colleagues). We use semver for our versioning of release/pre-releases and I'd like to prevent us having two different versioning schemes.

The issue that I currently see is that the pre-release version after e.g. `1.2.0` should be e.g. `1.2.1-<xx>-<hash>`, not `1.2.0-<xx>-<hash>` as is returned by `git --describe`.

Would you be open to support the (optional) creation of semver-compliant versions, e.g. via a parameter? I'd be happy to write a PR for that.

In the same vein it would be great if the current branch name could be included in the information gained from git.

**Comment by de-vri-es** [comment]
Hey!

> I'd like to use git-version to generate version identifiers for e.g. CI builds (as they are downloaded and used by colleagues). We use semver for our versioning of release/pre-releases and I'd like to prevent us having two different versioning schemes.
> 
> The issue that I currently see is that the pre-release version after e.g. `1.2.0` should be e.g. `1.2.1-<xx>-<hash>`, not `1.2.0-<xx>-<hash>` as is returned by `git --describe`.

This is partially because git cannot know what the next version will be. Git (and `git_version!()`) cannot know if next version will be `1.2.1`. It could also be `1.3.0` or `2.0.0`.

It's also not necessarily the case that the number of commits since the previous tag should be used as-is for the pre-release version component.

My suggestion: parse the information from `git_version!()` and apply your own rules to them.

**Comment by andreasWallnerIFX** [comment]
> This is partially because git cannot know what the next version will be. Git (and `git_version!()`) cannot know if next version will be `1.2.1`. It could also be `1.3.0` or `2.0.0`.

That git can't know is clear, but from semver POV this doesn't matter: since anything with a pre-release identifier is considered unstable and doesn't make any compatibility guarantees its always fine to just increment the minor version.

> My suggestion: parse the information from `git_version!()` and apply your own rules to them.

Totally fair if you'd prefer not to support this, thanks for taking the time to respond.
